/** @type {import('tailwindcss').Config} */
// Design tokens lifted verbatim from the Stitch export (stitch_ai_cashflow_guardian).
// The palette is byte-identical across all 65 exported screens, so this is the single source of truth.
module.exports = {
  content: ['./app/**/*.{js,jsx,ts,tsx}', './src/**/*.{js,jsx,ts,tsx}'],
  presets: [require('nativewind/preset')],
  theme: {
    extend: {
      colors: {
        'surface-variant': '#333538',
        'on-tertiary-container': '#c51740',
        'on-tertiary': '#67001b',
        error: '#ffb4ab',
        'surface-container-highest': '#333538',
        'surface-container-low': '#1a1c1f',
        'surface-container': '#1e2023',
        'surface-container-lowest': '#0c0e11',
        'on-primary-fixed': '#171e00',
        'tertiary-container': '#ffdadb',
        'on-surface': '#e2e2e6',
        'secondary-container': '#04d388',
        tertiary: '#ffffff',
        'on-secondary-container': '#005534',
        'surface-dim': '#111317',
        secondary: '#44f0a1',
        'surface-tint': '#b0d500',
        'inverse-primary': '#536600',
        'tertiary-fixed': '#ffdadb',
        'on-secondary-fixed-variant': '#005232',
        'on-error-container': '#ffdad6',
        'on-tertiary-fixed': '#40000d',
        'on-error': '#690005',
        primary: '#ffffff',
        'inverse-surface': '#e2e2e6',
        'on-primary-fixed-variant': '#3e4c00',
        'on-secondary': '#003921',
        'on-primary': '#2a3400',
        'on-background': '#e2e2e6',
        surface: '#111317',
        'primary-fixed': '#cbf230',
        'on-tertiary-fixed-variant': '#920029',
        'error-container': '#93000a',
        'on-surface-variant': '#c5c9ae',
        'on-secondary-fixed': '#002111',
        'surface-bright': '#37393d',
        'secondary-fixed-dim': '#2ee194',
        'secondary-fixed': '#57feaf',
        'tertiary-fixed-dim': '#ffb2b7',
        'primary-container': '#cbf230',
        'primary-fixed-dim': '#b0d500',
        'outline-variant': '#454934',
        'inverse-on-surface': '#2f3034',
        'surface-container-high': '#282a2d',
        'on-primary-container': '#586c00',
        background: '#111317',
        outline: '#8f937a',
      },
      borderRadius: {
        DEFAULT: '0.25rem',
        lg: '0.5rem',
        xl: '0.75rem',
        full: '9999px',
      },
      spacing: {
        'space-xs': '0.25rem',
        'space-sm': '0.5rem',
        'space-md': '1rem',
        'space-lg': '1.5rem',
        'space-xl': '2rem',
        margin: '1.25rem',
        gutter: '1rem',
      },
      fontFamily: {
        'display-hero': ['PlusJakartaSans_700Bold'],
        'display-hero-mobile': ['PlusJakartaSans_700Bold'],
        'numeral-display': ['PlusJakartaSans_700Bold'],
        'headline-lg': ['PlusJakartaSans_700Bold'],
        'headline-md': ['PlusJakartaSans_600SemiBold'],
        'headline-sm': ['PlusJakartaSans_600SemiBold'],
        'label-lg': ['PlusJakartaSans_600SemiBold'],
        'label-md': ['PlusJakartaSans_600SemiBold'],
        'label-sm': ['PlusJakartaSans_600SemiBold'],
        'body-lg': ['PlusJakartaSans_500Medium'],
        'body-md': ['PlusJakartaSans_400Regular'],
        'body-sm': ['PlusJakartaSans_400Regular'],
      },
      fontSize: {
        'display-hero': ['36px', { lineHeight: '44px' }],
        'display-hero-mobile': ['32px', { lineHeight: '40px' }],
        'numeral-display': ['34px', { lineHeight: '40px' }],
        'headline-lg': ['24px', { lineHeight: '32px' }],
        'headline-md': ['20px', { lineHeight: '28px' }],
        'headline-sm': ['18px', { lineHeight: '24px' }],
        'body-lg': ['16px', { lineHeight: '24px' }],
        'body-md': ['14px', { lineHeight: '20px' }],
        'body-sm': ['12px', { lineHeight: '16px' }],
        'label-lg': ['14px', { lineHeight: '20px' }],
        'label-md': ['12px', { lineHeight: '16px' }],
        'label-sm': ['10px', { lineHeight: '14px' }],
      },
    },
  },
  plugins: [],
};
